{
    "_type": "pyessv._model.term", 
    "canonicalName": "qc-flag-channel-4-failure", 
    "createDate": "2018-03-09 00:00:00+00:00", 
    "data": {
        "dimension": "time", 
        "flagMeanings": "not_used good_data  bad_data_channel_failure suspect_data_time_stamp_error", 
        "flagValues": "0b,1b, 2b, 3b", 
        "longName": "Data Quality flag: Receiver channel 4 failed", 
        "name": "qc_flag_channel_4_failure", 
        "type": "byte", 
        "units": "1"
    }, 
    "idx": 11, 
    "label": "qc_flag_channel_4_failure", 
    "rawName": "qc_flag_channel_4_failure", 
    "status": "pending", 
    "uid": "7cbce559-4512-4734-b226-76d9322a9a0d"
}